- internal/build/render/table.go
- internal/build/render/table_test.go
- internal/build/token/base.go
- internal/build/token/column.go
- internal/build/token/table.go
- Implements NewTable with inline and explicit alias handling
- Adds NewErroredTable constructor for clean error propagation
- Ensures comma-separated input and alias mismatch produce structured errors
- Includes Raw() and String() methods for diagnostics and rendering support
- Table token now matches Column’s robustness and builder readiness
Since: v1.6.0
> feat(token): finalize Table token with alias parsing and error support

- internal/build/token/base.go
- internal/build/token/column.go
- internal/build/token/column_test.go
- Adds #Example sections to Column.Render and BaseToken.RenderName/RenderAlias
- Uses explicit Postgres dialect setup in all examples
- Adds test coverage for Render() including aliased, qualified, and full combinations
- Aligns test naming and documentation with real-world usage and output
> docs(column): complete GoDoc and add Render tests with dialect examples

- builder/select_test.go
- internal/build/token/table.go
- Refines alias conflict detection logic using SetErrorWith
- Ensures Source is properly set for all expression types
- Handles edge cases: leading 'AS', empty expressions, comma usage
- Maintains consistency with Column parsing strategy
> refactor(table): align alias and error handling with Column token

- internal/build/token/table.go
- internal/build/token/table_test.go
- Implements Table.Render(dialect) for quoted output
- Supports alias rendering using AS syntax
- Handles nil and invalid cases gracefully
- Adds full test coverage using Postgres dialect
- Aligns render logic with Column token behavior
> feat(table): add Render method with dialect support

- docs/dev/build/base_token.md
- docs/dev/build/token.md
- internal/build/token/base.go
- internal/build/token/base_test.go
- Introduced alias-aware constructor for BaseToken with inline and explicit alias resolution
- Added robust validations in NewBaseToken (empty input, AS keyword, comma errors, conflicts)
- Refactored BaseToken tests to cover alias conflict and inline alias parsing
- Documented BaseToken usage in a dedicated guide (base_token.md)
- Updated token.md to reference external BaseToken guide for maintainability
This prepares the token system for future modularization and shared parsing logic across Column, Table, and Condition tokens.
> feat(token): add BaseToken guide and alias resolution support

- docs/dev/build/base_token.md
- internal/build/token/base.go
- internal/build/token/base_test.go
- internal/build/token/generic.go
- internal/core/contract/renderable.go
- Renamed BaseToken field `source` to `input` (incl. GetSource → GetInput) to avoid naming conflicts with data sources
- Introduced `contract.Renderable` in internal/core/contracts/renderable.go, grouping Raw, RenderName, RenderAlias, and String methods
- Updated BaseToken (internal/build/token/base.go): • Adjusted RenderName and RenderAlias to accept `contract.Quoter` instead of `driver.Dialect` • Refactored Raw() and String() to satisfy `contract.Renderable` • Marked HasError() and SetErrorWith() as deprecated in favor of IsErrored() and SetError() • Added GoDoc “Since: v1.7.0” annotations on new/renamed methods • Renamed `source` field to `input` for diagnostics
- Updated unit tests (internal/build/token/base_test.go): • Adjusted calls to RenderName/RenderAlias to pass a Quoter • …
> feat(token): rename Source to Input, extract Renderable interface, and update BaseToken

- common/number/parser.go
- common/number/parser_test.go
- Added support for boolean inputs in ParseFrom, converting `true` to 1 and `false` to 0.
- Updated GoDoc to document bool support and conversion behavior.
- Added unit tests covering boolean true/false cases.
- Maintained existing coverage for all numeric and string input types.
- Ensured no external testing libraries are used in tests.
> feat(number): extend ParseFrom to support bool values

- db/dialect/base.go
- Added BaseDialect struct implementing Dialect interface with common default behaviors:
- Identifier quoting using double quotes
- Literal quoting supporting strings, numbers, bools, nil, and time.Time with escaping
- Placeholder syntax defaulting to "?"
- Pagination syntax using standard LIMIT/OFFSET clauses
- SupportsReturning returns false by default
- Provides a generic SQL dialect foundation for building concrete dialect implementations
- Includes full GoDoc comments for clarity and maintainability
> feat(dialect): implement BaseDialect with default SQL behaviors

- common/extension/date/cleaner_test.go
- common/extension/date/internal/string.go
- common/extension/date/internal/string_test.go
- common/extension/date/parser_test.go
- common/extension/parser.go
- common/extension/parser_test.go
- Introduce parser.go at package root to provide ergonomic shortcuts: • Boolean(v any) (bool, error) → delegates to boolean.ParseFrom • Float(v any) (float64, error) → delegates to float.ParseFrom • Decimal(v any, precision int) (float64, error) → delegates to decimal.ParseFrom • Date(v any) (time.Time, error) → delegates to date.ParseFrom
- Reduces boilerplate imports (boolean/float/decimal/date) for common cases
- Thin façade only; underlying parsing logic unchanged
✅ Tests (parser_test.go, file→methods→cases, PascalCase) with full coverage:
• Boolean:
– Accepts bools, numbers, canonical strings (“true”, “false”, “1”, “0”, etc.)
– Extended forms (“yes”/“no”, “on”/“off”, “y”/“n”, “t”/“f”)
– Rejects invalid strings and nil
• Float:
– Parses float64, float32, integers, numeric strings …
> feat(common/extension): add parser shortcuts for Boolean, Float, Decimal, Date

- CHANGELOG.md
- README.md
- docs/index.md
- mkdocs.yml
- releases/index.md
- releases/release-notes-v1.10.0.md
- releases/release-notes-v1.11.0.md
- Add CHANGELOG entry for v1.11.0: • Parsing shortcuts for Boolean, Float, Decimal, Date • Deterministic date cleaning (CleanAndParse, CleanAndParseAsString, strict YYYYMMDD prefix) • Boolean parser extended tokens and nil validation • SQL builder/token/dialect enhancements (Column→Field, FieldCollection, Base/Postgres dialects) • Package rename: math → extension
- Add standalone v1.11.0 release notes file for GitHub releases
- Update documentation site with new parsing shortcuts and migration notes
- Ensure consistency across CHANGELOG, release notes, and site docs
> docs(release): add v1.11.0 changelog, release notes, and site updates

- common/extension/decimal/README.md
- common/extension/decimal/doc.go
- common/extension/decimal/examples_test.go
- Introduce example_test.go with GoDoc examples
- Cover parsing from string, integer, and float inputs
- Ensure examples demonstrate decimal.Decimal API (`String`, `StringFixed`)
- Guarantees examples compile and appear in GoDoc/pkg.go.dev
> test(common/extension/decimal): add usage examples

- common/extension/float/README.md
- common/extension/float/doc.go
- common/extension/float/examples_test.go
- common/extension/float/parser.go
- Introduce example_test.go with GoDoc examples
- Demonstrate ParseFrom for string, integer, and float inputs
- Include formatting example (to 2 decimal places)
- Ensure examples compile and are visible in GoDoc/pkg.go.dev
> test(common/extension/float): add usage examples

- db/builder/select.go
- db/token/doc.go
- db/token/example_test.go
- db/token/field.go
- db/token/field.md
- db/token/field_test.go
- Introduce Field.Debug() for compact diagnostic output:
✅ Field("COUNT(*) AS total"): [raw: true, aliased: true, errored: false]
⛔️ Field("true"): [raw: false, aliased: false, errored: true] – input type unsupported: bool
- Update Field.String() to include ✅/⛔️ icons and handle wrong initialization explicitly
- Extend example_test.go with demonstrations of String() and Debug() for valid and invalid fields
- Revise field.md guide to document new String()/Debug() behavior with examples
> feat(token/field): add Debug() and enhance String() with ✅/⛔️ diagnostics

- CHANGELOG.md
- Dockerfile-documentation
- db/builder/README.md
- db/builder/doc.go
- db/builder/example_test.go
- db/builder/select.go
- db/builder/select_test.go
- mkdocs.yml
- releases/index.md
- releases/release-notes-v1.13.0.md
- SelectBuilder:
- Introduce Where(), And(), and Or() methods using collection.Collection[string]
- Where() resets conditions; And()/Or() append
- Normalize multiple conditions in a single call (e.g., Where("a","b") → a AND b)
- Build() simplified to join stored conditions directly
- Defensive handling for manual initialization (&SelectBuilder{}) with tests
- Full test suite: defaults, single/multiple conditions, ignore empty, reset, append, OR first, AND first, mixed AND/OR, and manual init
- Field:
- Add Debug() for compact diagnostic output with ✅/⛔️ icons and flags
- Enhance String() with ✅/⛔️ icons and explicit "wrong initialization"
- Update example_test.go with Debug()/String() usage
- Update field.md guide documenting new behavior
Result: 100% coverage for builder.SelectBuilder …
> feat(db/builder/select, token/field): add WHERE/AND/OR support and field diagnostics

- db/builder/README.md
- db/builder/doc.go
- db/builder/example_test.go
- db/builder/select.go
- db/builder/select_test.go
- Introduce .OrderBy() to set ORDER BY clause (resets previous ordering)
- Introduce .ThenOrderBy() to append additional ordering fields
- Add nil-safety for both conditions and sorting collections in Build()
- Update README.md and doc.go with strict examples and ordering docs
- Add example_test.go coverage for ordering to enforce doc consistency
> feat(builder): add ORDER BY support with OrderBy/ThenOrderBy

- CHANGELOG.md
- db/builder/README.md
- db/builder/doc.go
- db/builder/example_test.go
- db/builder/select.go
- db/builder/select_test.go
- releases/release-notes-v1.13.0.md
- Introduced HAVING clause handling with:
- Having(...string): reset and set conditions
- AndHaving(...string): append conditions with AND
- OrHaving(...string): append conditions with OR
- Normalizes multiple conditions with AND, ignores empty values
- Rendered immediately after GROUP BY and before ORDER BY
- Extended Build() to include HAVING
- Added full test suite (NilCollection, Single, Multiple, IgnoreEmpty, ResetCollection, And, Or)
- Added example in example_test.go (ExampleSelectBuilder_having)
- Updated README.md, doc.go, and CHANGELOG with Having section
- Release notes updated to document Having support
> feat(builder/select): add Having clause support to SelectBuilder

- .github/CONTRIBUTING.md
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Added CONTRIBUTING.md (full guide) and CONTRIBUTING_QUICK.md (checklist)
- Added PULL_REQUEST_TEMPLATE.md with contributor quick reference
- Updated PR template to mark fun commit phrase as optional
- Added FUNDING.yml with sponsor/custom support links
- Refreshed issue templates under .github/ISSUE_TEMPLATE:
- bug_report.md (modernized for Entiqon)
- documentation_issue.md (clarified for Entiqon)
- feature_request.md (clarified for Entiqon)
> chore(github): add contributing guides, templates, and funding config

- CHANGELOG.md
- db/builder/select.go
- db/builder/select_test.go
- db/contract/README.md
- db/contract/doc.go
- db/contract/errorable.go
- db/contract/example_test.go
- db/token/field/field.go
- db/token/field/field_test.go
- db/token/table/table.go
- releases/release-notes-v1.13.0.md
Examples:  
```text
```
- Optional: add a fun closing phrase in commits, e.g.:  
```
```
--- …
> feat(contract): extend Errorable with SetError for token state mutation

- CHANGELOG.md
- README.md
- db/README.md
- db/builder/example_test.go
- db/builder/select.go
- db/builder/select_test.go
- db/token/README.md
- db/token/doc.go
- db/token/field/README.md
- db/token/field/contract.go
- db/token/field/doc.go
- db/token/field/example_test.go
- db/token/field/field.go
- db/token/field/field_test.go
- db/token/table/README.md
- releases/release-notes-v1.13.0.md
Examples:  
```text
```
- Optional: add a fun closing phrase in commits, e.g.:  
```
```
--- …
> release(v1.13.0): finalize field refinements, contracts, and docs restructure

- db/contract/validable.go
Examples:  
```text
```
- Optional: add a fun closing phrase in commits, e.g.:  
```
```
--- …
> feat(contract): add ValidateType helper to validable.go

- CHANGELOG.md
- db/token/helpers/doc.go
- db/token/helpers/example_test.go
- db/token/helpers/helpers_test.go
- db/token/helpers/identifier.go
- releases/release-notes-v1.14.0.md
Examples:  
```text
```
- Optional: add a fun closing phrase in commits, e.g.:  
```
```
--- …
> refactor(helpers): streamline ResolveExpression with classifier-driven branching

- CHANGELOG.md
- Dockerfile-documentation
- db/errors/README.md
- db/errors/doc.go
- db/errors/errors.go
- db/errors/errors_test.go
- db/errors/example_test.go
- db/errors/unsupported_type.go
- mkdocs.yml
- releases/release-notes-v1.15.0.md
- Tests follow `file → methods → cases` pattern with **PascalCase**.
Examples:  
```text
```
- Optional: add a fun …
> feat(errors): add documentation and examples for sentinel errors
